### ISSUE TITLE
Pip3 error

### ISSUE THREAD

**Issue by doglife007** [jm33-m0/massExpConsole#15]
```
./mec.py 
Traceback (most recent call last):
  File "./mec.py", line 7, in <module>
    from lib.cli import main
  File "/root/Downloads/massExpConsole/lib/cli/main.py", line 15, in <module>
    import lib.tools.baidu as baidu
  File "/root/Downloads/massExpConsole/lib/tools/baidu.py", line 12, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'
```
i try pip3 install -r requirements.txt
but nothing 
```
 /usr/bin/ld: cannot find -lncurses
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ysxbim9g/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tkrrm725-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ysxbim9g/readline/
```

**Comment by jm33-m0** [comment]
Obviously it's not an issue with scripts, please check your Python installation, reinstall all necessary Python packages, eg. `python3`, `python3-setuptools`, `python3-pip` in Debian based distros
