### ISSUE TITLE
pip3  requirement not working I guess! 

### ISSUE THREAD

**Issue by geekfrom90s** [jm33-m0/massExpConsole#17]
that's what i get when trying `pip3 install -r requirements.txt`

```
creating build/lib.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-G3waep/python3.5-3.5.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/Modules/3.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-x86_64-3.5/readline.cpython-35m-x86_64-linux-gnu.so
    /usr/bin/ld: cannot find -lncurses
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1an0d0gk/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8jpnr12z-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-1an0d0gk/readline/
```

**Comment by geekfrom90s** [comment]
I solved the above issue by `sudo apt-get install lib32ncurses5-dev`
and i faced another one when opening `mec.py`

```
Traceback (most recent call last):
  File "mec.py", line 10, in <module>
    main.run()
  File "/root/massExpConsole-master/lib/cli/main.py", line 419, in run
    main()
  File "/root/massExpConsole-master/lib/cli/main.py", line 376, in main
    colors.END)).strip()
  File "<string>", line 1, in <module>
NameError: name 'n' is not defined
```

**Comment by jm33-m0** [comment]
obviously, there's something wrong with your python3 installation, i recommend you reinstalling the latest version of python3 before reporting bugs here

**Comment by geekfrom90s** [comment]
thank you for your info 
I ran it with this command (python3...)
