### ISSUE TITLE
install.py fails to run when `distro` is unavailable

### ISSUE THREAD

**Issue by jm33-m0** [jm33-m0/massExpConsole#36]
```
# python3 install.py
Collecting distro
  Downloading https://files.pythonhosted.org/packages/ea/35/82f79b92fa4d937146c660a6482cee4f3dfa1f97ff3d2a6f3ecba33e712e/distro-1.4.0-py2.py3-none-any.whl
Installing collected packages: distro
Successfully installed distro-1.4.0
Traceback (most recent call last):
  File "install.py", line 18, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install.py", line 23, in <module>
    if mod_exists("distro"):
NameError: name 'mod_exists' is not defined
```

**Comment by jm33-m0** [comment]
`mod_exists` function should be put ahead of `import distro`
