### ISSUE TITLE
issue with baidu

### ISSUE THREAD

**Issue by finch254** [jm33-m0/massExpConsole#8]
All requirements are installed but if i run mec.py it brings this error. how do i fix????

Traceback (most recent call last):
  File "./mec.py", line 13, in <module>
    import util.baidu as baidu
  File "/root/massExpConsole/util/baidu.py", line 12, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'

**Comment by jm33-m0** [comment]
obviously you have to install `bs4`, `pip3 install bs4` can do that for you
